name: Monitoramento de Passagens (Amadeus)

on:
  schedule:
    - cron: "0 */4 * * *"   # roda a cada 4 horas
  workflow_dispatch:        # permite rodar manualmente

jobs:
  monitor-passagens:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validar secrets
        run: |
          for V in AMADEUS_API_KEY AMADEUS_API_SECRET TELEGRAM_BOT_TOKEN TELEGRAM_CHAT_ID; do
            if [ -z "${!V}" ]; then
              echo "::error::Secret $V não definido"
              exit 1
            fi
          done

      - name: Rodar monitor (Amadeus)
        env:
          AMADEUS_API_KEY: ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          AMADEUS_ENV: test   # ou "prod" se usar produção
        run: |
          set -x
          python monitor_passagens.py