name: Monitoramento de Passagens (Amadeus)

on:
  schedule:
    - cron: "0 */4 * * *"  # roda a cada 4 horas (UTC). Ajuste se quiser.
  workflow_dispatch:

permissions:
  contents: write  # para comitar data/history.csv se você fizer histórico no monitor

jobs:
  monitor-passagens:
    runs-on: ubuntu-latest
    concurrency: monitor-passagens
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ping Telegram (teste)
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python - <<'PY'
          import os, requests, sys
          t=os.getenv("BOT_TOKEN"); c=os.getenv("CHAT_ID")
          if not t or not c: sys.exit("Faltam BOT_TOKEN/CHAT_ID")
          r=requests.post(f"https://api.telegram.org/bot{t}/sendMessage",
                          json={"chat_id": int(c), "text": "✅ Conectado ao Telegram (produção)."}, timeout=20)
          print("HTTP", r.status_code, r.text[:200]); r.raise_for_status()
          PY

      - name: Run monitor (Amadeus - produção)
        env:
          # --- secrets obrigatórios ---
          AMADEUS_API_KEY:      ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET:   ${{ secrets.AMADEUS_API_SECRET }}
          TELEGRAM_BOT_TOKEN:   ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:     ${{ secrets.TELEGRAM_CHAT_ID }}

          # --- produção ---
          AMADEUS_ENV:          production  # usa https://api.amadeus.com

          # --- parâmetros do monitor ---
          ORIGEM: GYN
          # Lista de TODAS as capitais do Brasil (IATA principal) EXCETO GYN
          DESTINOS: BSB,GIG,SDU,CGH,GRU,VIX,SSA,REC,FOR,NAT,MCZ,AJU,SLZ,THE,FLN,POA,CWB,CNF,CGR,CGB,BEL,JPA,MAO,BVB,PVH,RBR,PMW,MCP
          DAYS_AHEAD_FROM: "10"
          DAYS_AHEAD_TO:   "90"
          SAMPLE_DEPARTURES: "3"
          CURRENCY: "BRL"
          MAX_OFFERS: "5"
          REQUEST_DELAY: "1.5"   # aumente se notar 429 (rate limit)

        run: |
          python monitor_passagens.py