name: Monitoramento de Passagens (PROD)

on:
  schedule:
    - cron: "0 */4 * * *"   # a cada 4h (UTC)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    concurrency:
      group: monitor-passagens-prod
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Diagnóstico secrets
        env:
          AMADEUS_API_KEY:    ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
        run: |
          echo "AMADEUS_API_KEY: $([ -n "$AMADEUS_API_KEY" ] && echo OK || echo MISSING)"
          echo "AMADEUS_API_SECRET: $([ -n "$AMADEUS_API_SECRET" ] && echo OK || echo MISSING)"

      - name: Rodar monitor (produção)
        env:
          AMADEUS_API_KEY:    ${{ secrets.AMADEUS_API_KEY }}
          AMADEUS_API_SECRET: ${{ secrets.AMADEUS_API_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}

          AMADEUS_ENV: production         # <<< PRODUÇÃO
          ORIGEM: GYN
          DESTINOS: CAPITAIS_BR           # todas as capitais (mapeadas para IATA)
          DAYS_AHEAD_FROM: "10"
          DAYS_AHEAD_TO:   "90"
          SAMPLE_DEPARTURES: "3"
          MAX_OFFERS: "5"
          REQUEST_DELAY: "2.2"            # aumente se bater rate limit
          CURRENCY: BRL
          MAX_PRECO_PP: "1200"
          MIN_DISCOUNT_PCT: "0.25"
        run: python monitor_passagens.py

      - name: Commit histórico (se mudou)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(monitor-prod): atualizar histórico de preços"
          file_pattern: data/history.csv