name: Relatório Diário de Preços

on:
  schedule:
    - cron: "0 12 * * *"   # todos os dias às 12:00 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Gerar e enviar relatório
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
          HISTORY_PATH:       data/history.csv
          REPORT_DAYS_BACK:   "1"           # 1 = ontem (UTC)
          TG_PARSE_MODE:      "Markdown"    # ou "MarkdownV2"
        run: |
          python gerar_relatorio.py